import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { MediaService } from '../media/media.service';
@Injectable() export class AccountService {
 constructor(private readonly prisma:PrismaService, private readonly media: MediaService){}
 profile(id:string){return this.prisma.user.findUniqueOrThrow({where:{id},select:{id:true,email:true,firstName:true,lastName:true,phone:true,avatarUrl:true,emailVerifiedAt:true,createdAt:true}})}
 updateProfile(id:string,data:{firstName:string;lastName:string;phone?:string}){return this.prisma.user.update({where:{id},data:{firstName:data.firstName.trim(),lastName:data.lastName.trim(),phone:data.phone?.trim()},select:{id:true,email:true,firstName:true,lastName:true,phone:true,avatarUrl:true}})}
 async updateAvatar(id: string, file?: Express.Multer.File) { const uploaded = await this.media.upload(id, file); return this.prisma.user.update({ where: { id }, data: { avatarUrl: uploaded.url }, select: { id: true, avatarUrl: true } }); }
 addresses(userId:string){return this.prisma.address.findMany({where:{userId},orderBy:[{isDefaultShipping:'desc'},{createdAt:'desc'}]})}
 async addAddress(userId:string,data:Prisma.AddressUncheckedCreateWithoutUserInput){return this.prisma.$transaction(async tx=>{if(data.isDefaultShipping)await tx.address.updateMany({where:{userId},data:{isDefaultShipping:false}});if(data.isDefaultBilling)await tx.address.updateMany({where:{userId},data:{isDefaultBilling:false}});return tx.address.create({data:{...data,userId}})})}
 async editAddress(userId:string,id:string,data:Prisma.AddressUncheckedUpdateInput){return this.prisma.$transaction(async tx=>{const current=await tx.address.findFirst({where:{id,userId}});if(!current)throw new NotFoundException({code:'ADDRESS_NOT_FOUND',message:'Address was not found'});if(data.isDefaultShipping)await tx.address.updateMany({where:{userId,id:{not:id}},data:{isDefaultShipping:false}});if(data.isDefaultBilling)await tx.address.updateMany({where:{userId,id:{not:id}},data:{isDefaultBilling:false}});return tx.address.update({where:{id},data})})}
 async removeAddress(userId:string,id:string){const result=await this.prisma.address.deleteMany({where:{id,userId}});if(!result.count)throw new NotFoundException({code:'ADDRESS_NOT_FOUND',message:'Address was not found'})}
 sessions(userId:string){return this.prisma.userSession.findMany({where:{userId,revokedAt:null,expiresAt:{gt:new Date()}},select:{id:true,userAgent:true,ipAddress:true,createdAt:true,lastUsedAt:true,expiresAt:true},orderBy:{lastUsedAt:'desc'}})}
 async revokeSession(userId:string,id:string){const result=await this.prisma.userSession.updateMany({where:{id,userId,revokedAt:null},data:{revokedAt:new Date()}});if(!result.count)throw new NotFoundException({code:'SESSION_NOT_FOUND',message:'Session was not found'})}
 exportData(userId:string){return this.prisma.user.findUniqueOrThrow({where:{id:userId},select:{id:true,email:true,firstName:true,lastName:true,phone:true,createdAt:true,addresses:true,orders:{include:{items:true,statusHistory:true,refunds:true,returns:{include:{items:true}}}},reviews:true,notifications:true}})}
 coupons(userId:string){return this.prisma.couponUsage.findMany({where:{userId},orderBy:{usedAt:'desc'},include:{coupon:{select:{code:true,type:true,value:true}},order:{select:{id:true,orderNumber:true}}}})}
 refunds(userId:string){return this.prisma.refund.findMany({where:{order:{userId}},orderBy:{createdAt:'desc'},include:{order:{select:{id:true,orderNumber:true}},payment:{select:{provider:true}}}})}
 requestDeletion(userId:string){return this.prisma.$transaction([this.prisma.user.update({where:{id:userId},data:{status:'PENDING_DELETION',deletedAt:new Date()}}),this.prisma.userSession.updateMany({where:{userId},data:{revokedAt:new Date()}})])}
 consents(userId: string) { return this.prisma.userConsent.findMany({ where: { userId }, orderBy: { createdAt: 'desc' } }); }
 recordConsent(userId: string, ip: string, userAgent: string | string[] | undefined, data: { type: string; version: string; accepted: boolean }) { return this.prisma.userConsent.upsert({ where: { userId_type_version: { userId, type: data.type.trim(), version: data.version.trim() } }, update: { accepted: data.accepted, ipAddress: ip, userAgent: Array.isArray(userAgent) ? userAgent[0] : userAgent }, create: { userId, type: data.type.trim(), version: data.version.trim(), accepted: data.accepted, ipAddress: ip, userAgent: Array.isArray(userAgent) ? userAgent[0] : userAgent } }); }
}
