import { Processor, WorkerHost } from '@nestjs/bullmq';
import { ConfigService } from '@nestjs/config';
import { Prisma } from '@prisma/client';
import type { Job } from 'bullmq';
import nodemailer from 'nodemailer';
import { PrismaService } from '../prisma/prisma.service';

const templates: Record<string, (values: Record<string, string>) => { subject: string; body: string }> = {
  verify: (values) => ({ subject: 'Verify your Burujan email', body: `Welcome to Burujan. Verify your email using this secure link: ${values.url}` }),
  'verify-email-change': (values) => ({ subject: 'Confirm your new email address', body: `Confirm this email address using the secure link within one hour: ${values.url}\n\nIf you did not request this change, secure your account immediately.` }),
  reset: (values) => ({ subject: 'Reset your Burujan password', body: `A password reset was requested. Use this secure link within one hour: ${values.url}\n\nIf you did not request it, you can ignore this message.` }),
  order: (values) => ({ subject: `Order ${values.orderNumber} received`, body: `Thank you for your order ${values.orderNumber}. Track it from your Burujan account.` }),
  'order-confirmed': (values) => ({ subject: `Order ${values.orderNumber} confirmed`, body: `Your order ${values.orderNumber} has been confirmed and is being prepared.` }),
  'order-processing': (values) => ({ subject: `Order ${values.orderNumber} is processing`, body: `Your order ${values.orderNumber} is now being prepared.` }),
  'order-shipped': (values) => ({ subject: `Order ${values.orderNumber} shipped`, body: `Your order ${values.orderNumber} is on its way. Tracking: ${values.trackingNumber || 'available in your account'}.` }),
  'order-delivered': (values) => ({ subject: `Order ${values.orderNumber} delivered`, body: `Your order ${values.orderNumber} has been delivered. We hope you enjoy it.` }),
  'order-cancelled': (values) => ({ subject: `Order ${values.orderNumber} cancelled`, body: `Your order ${values.orderNumber} was cancelled. Any eligible payment reversal will be processed separately.` }),
  refund: (values) => ({ subject: `Refund issued for ${values.orderNumber}`, body: `A refund of ${values.amount} was issued for order ${values.orderNumber}.` }),
  return: (values) => ({ subject: `Return update for ${values.orderNumber}`, body: `Your return request for order ${values.orderNumber} is now ${values.status}.` }),
  newsletter: (values) => ({ subject: 'Confirm your Burujan newsletter subscription', body: `Confirm your newsletter subscription using this link: ${values.url}` }),
  contact: (values) => ({ subject: `Contact form: ${values.subject}`, body: `A contact message was received from ${values.name} (${values.email}).\n\n${values.message}` }),
  'contact-received': (values) => ({ subject: 'We received your message', body: `Thanks for contacting Burujan. We received your message about “${values.subject}” and will reply as soon as possible.` }),
};
const escapeHtml = (value: string) => value.replace(/[&<>]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[character] ?? character);

@Processor('email')
export class EmailProcessor extends WorkerHost {
  private readonly transport;
  private readonly from: string;
  constructor(config: ConfigService) { super(); this.from = config.getOrThrow('SMTP_FROM'); this.transport = nodemailer.createTransport({ host: config.getOrThrow('SMTP_HOST'), port: Number(config.get('SMTP_PORT', 587)), secure: Number(config.get('SMTP_PORT', 587)) === 465, auth: config.get('SMTP_USER') ? { user: config.get('SMTP_USER'), pass: config.get('SMTP_PASSWORD') } : undefined }); }
  async process(job: Job<{ to: string; template: string; variables: Record<string, string> }>) { const render = templates[job.data.template]; if (!render) throw new Error(`Unknown email template: ${job.data.template}`); const email = render(job.data.variables); await this.transport.sendMail({ from: this.from, to: job.data.to, subject: email.subject, text: email.body, html: `<div style="font-family:Arial;max-width:600px;margin:auto"><h1>BURUJAN</h1><p style="white-space:pre-line;line-height:1.6">${escapeHtml(email.body)}</p></div>` }); return { sent: true }; }
}

@Processor('maintenance')
export class MaintenanceProcessor extends WorkerHost {
  constructor(private readonly prisma: PrismaService) { super(); }
  async process(job: Job) { if (job.name === 'release-reservations') return this.release(); if (job.name === 'expire-promotions') return this.prisma.coupon.updateMany({ where: { active: true, expiresAt: { lte: new Date() } }, data: { active: false } }); if (job.name === 'abandoned-carts') return this.abandoned(); if (job.name === 'low-stock-alerts') return this.lowStock(); if (job.name === 'process-account-deletions') return this.processDeletions(); throw new Error(`Unknown maintenance job: ${job.name}`); }
  private async processDeletions() { const cutoff = new Date(Date.now() - 30 * 86_400_000); const users = await this.prisma.user.findMany({ where: { status: 'PENDING_DELETION', deletedAt: { lte: cutoff } }, select: { id: true } }); let processed = 0; for (const user of users) { await this.prisma.$transaction(async (tx) => { await tx.address.deleteMany({ where: { userId: user.id } }); await tx.cart.deleteMany({ where: { userId: user.id } }); await tx.wishlist.deleteMany({ where: { userId: user.id } }); const reviews = await tx.review.findMany({ where: { userId: user.id }, select: { id: true } }); for (const review of reviews) { await tx.reviewMedia.deleteMany({ where: { reviewId: review.id } }); await tx.review.update({ where: { id: review.id }, data: { body: '[review removed by account deletion]', title: 'Removed review' } }); } await tx.user.update({ where: { id: user.id }, data: { email: `deleted+${user.id}@invalid.local`, firstName: 'Deleted', lastName: 'Customer', phone: null, avatarUrl: null, passwordHash: 'ACCOUNT_DELETED', emailVerifiedAt: null, twoFactorSecret: null, twoFactorEnabled: false } }); await tx.auditLog.create({ data: { actorId: null, action: 'account.deletion_completed', resourceType: 'User', resourceId: user.id } }); }); processed++; } return { processed }; }
  private async release() { const reservations = await this.prisma.inventoryReservation.findMany({ where: { expiresAt: { lte: new Date() }, releasedAt: null, convertedAt: null }, take: 100 }); let count = 0; for (const row of reservations) await this.prisma.$transaction(async (tx) => { const claim = await tx.inventoryReservation.updateMany({ where: { id: row.id, releasedAt: null, convertedAt: null }, data: { releasedAt: new Date() } }); if (!claim.count) return; await tx.inventory.update({ where: { id: row.inventoryId }, data: { available: { increment: row.quantity }, reserved: { decrement: row.quantity }, version: { increment: 1 } } }); await tx.inventoryTransaction.create({ data: { inventoryId: row.inventoryId, reason: 'RELEASE', availableDelta: row.quantity, reservedDelta: -row.quantity, referenceType: 'ORDER', referenceId: row.orderId } }); count++; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); return { released: count }; }
  private async abandoned() { const carts = await this.prisma.cart.findMany({ where: { userId: { not: null }, updatedAt: { lte: new Date(Date.now() - 24 * 3_600_000) }, items: { some: {} } }, select: { id: true, userId: true, updatedAt: true }, take: 100 }); let created = 0; for (const cart of carts) { const prior = await this.prisma.notification.findFirst({ where: { userId: cart.userId, type: 'ABANDONED_CART', createdAt: { gte: cart.updatedAt } } }); if (!prior) { await this.prisma.notification.create({ data: { userId: cart.userId!, channel: 'IN_APP', type: 'ABANDONED_CART', subject: 'Your cart is waiting', body: 'Items in your cart may sell out.', data: { cartId: cart.id } } }); created++; } } return { identified: carts.length, created }; }
  private async lowStock() { const candidates = await this.prisma.inventory.findMany({ take: 500, include: { variant: { select: { sku: true, product: { select: { name: true } } } } } }); const rows = candidates.filter((row) => row.available <= row.lowStockThreshold); const admins = await this.prisma.user.findMany({ where: { status: 'ACTIVE', roles: { some: { role: { OR: [{ name: 'SUPER_ADMIN' }, { permissions: { some: { permission: { key: 'inventory.read' } } } }] } } } }, select: { id: true } }); let created = 0; for (const row of rows) for (const admin of admins) { const prior = await this.prisma.notification.findFirst({ where: { userId: admin.id, type: 'LOW_STOCK', createdAt: { gte: new Date(Date.now() - 24 * 3_600_000) }, data: { path: '$.inventoryId', equals: row.id } } }); if (!prior) { await this.prisma.notification.create({ data: { userId: admin.id, channel: 'IN_APP', type: 'LOW_STOCK', subject: `Low stock: ${row.variant.sku}`, body: `${row.variant.product.name} has ${row.available} available.`, data: { inventoryId: row.id } } }); created++; } } return { checked: rows.length, created }; }
}
