import { ConflictException, Injectable } from '@nestjs/common';
import type { Prisma } from '@prisma/client';

@Injectable() export class InventoryService {
  async reserve(tx: Prisma.TransactionClient, variantId:string, quantity:number, referenceId:string, expiresAt:Date) {
    if(quantity<1) throw new ConflictException({code:'INVALID_QUANTITY',message:'Quantity must be positive'});
    const inventory=await tx.inventory.findUnique({where:{variantId}}); if(!inventory) throw new ConflictException({code:'OUT_OF_STOCK',message:'This variant is unavailable'});
    const changed=await tx.inventory.updateMany({where:{id:inventory.id,available:{gte:quantity}},data:{available:{decrement:quantity},reserved:{increment:quantity},version:{increment:1}}});
    if(changed.count!==1) throw new ConflictException({code:'OUT_OF_STOCK',message:'Requested quantity is unavailable'});
    await tx.inventoryTransaction.create({data:{inventoryId:inventory.id,reason:'RESERVATION',availableDelta:-quantity,reservedDelta:quantity,referenceType:'ORDER',referenceId}});
    await tx.inventoryReservation.create({data:{inventoryId:inventory.id,orderId:referenceId,quantity,expiresAt}});
  }
  async commitOrder(tx:Prisma.TransactionClient,orderId:string){const reservations=await tx.inventoryReservation.findMany({where:{orderId,releasedAt:null,convertedAt:null}});for(const reservation of reservations){const claim=await tx.inventoryReservation.updateMany({where:{id:reservation.id,releasedAt:null,convertedAt:null},data:{convertedAt:new Date()}});if(!claim.count)continue;await tx.inventory.update({where:{id:reservation.inventoryId},data:{reserved:{decrement:reservation.quantity},sold:{increment:reservation.quantity},version:{increment:1}}});await tx.inventoryTransaction.create({data:{inventoryId:reservation.inventoryId,reason:'ORDER',availableDelta:0,reservedDelta:-reservation.quantity,soldDelta:reservation.quantity,referenceType:'ORDER',referenceId:orderId}})}}
  async cancelOrder(tx:Prisma.TransactionClient,orderId:string){const reservations=await tx.inventoryReservation.findMany({where:{orderId}});for(const reservation of reservations){if(!reservation.releasedAt&&!reservation.convertedAt){const claim=await tx.inventoryReservation.updateMany({where:{id:reservation.id,releasedAt:null,convertedAt:null},data:{releasedAt:new Date()}});if(claim.count){await tx.inventory.update({where:{id:reservation.inventoryId},data:{available:{increment:reservation.quantity},reserved:{decrement:reservation.quantity},version:{increment:1}}});await tx.inventoryTransaction.create({data:{inventoryId:reservation.inventoryId,reason:'CANCELLATION',availableDelta:reservation.quantity,reservedDelta:-reservation.quantity,referenceType:'ORDER',referenceId:orderId}})}}else if(reservation.convertedAt&&!reservation.releasedAt){const claim=await tx.inventoryReservation.updateMany({where:{id:reservation.id,convertedAt:{not:null},releasedAt:null},data:{releasedAt:new Date()}});if(claim.count){await tx.inventory.update({where:{id:reservation.inventoryId},data:{available:{increment:reservation.quantity},sold:{decrement:reservation.quantity},version:{increment:1}}});await tx.inventoryTransaction.create({data:{inventoryId:reservation.inventoryId,reason:'CANCELLATION',availableDelta:reservation.quantity,soldDelta:-reservation.quantity,referenceType:'ORDER',referenceId:orderId}})}}}}
}
