import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
@Injectable()
export class ReviewsService {
  constructor(private readonly prisma: PrismaService) {}
  async mine(userId: string, page: number) { const limit = 20; const [data, total] = await this.prisma.$transaction([this.prisma.review.findMany({ where: { userId }, orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit, include: { product: { select: { name: true, slug: true } }, media: { include: { media: { select: { id: true, altText: true, mimeType: true, visibility: true } } } } } }), this.prisma.review.count({ where: { userId } })]); return { data, meta: { page, limit, total, totalPages: Math.ceil(total / limit) } }; }
  async create(userId: string, input: { productId: string; orderItemId: string; rating: number; title: string; body: string; mediaIds?: string[] }) { const item = await this.prisma.orderItem.findFirst({ where: { id: input.orderItemId, productId: input.productId, order: { userId, status: 'DELIVERED' } } }); if (!item) throw new ConflictException({ code: 'REVIEW_NOT_ELIGIBLE', message: 'Only delivered purchases can be reviewed' }); const mediaIds = input.mediaIds ?? []; if (mediaIds.length && await this.prisma.media.count({ where: { id: { in: mediaIds }, uploadedById: userId } }) !== mediaIds.length) throw new ConflictException({ code: 'REVIEW_MEDIA_INVALID', message: 'One or more review images are unavailable' }); return this.prisma.review.create({ data: { productId: input.productId, orderItemId: input.orderItemId, rating: input.rating, title: input.title, body: input.body, userId, verifiedPurchase: true, status: 'PENDING', media: { create: mediaIds.map((mediaId) => ({ mediaId })) } }, include: { media: { include: { media: true } } } }); }
  async vote(userId: string, reviewId: string, helpful: boolean) { return this.prisma.$transaction(async (tx) => { const review = await tx.review.findFirst({ where: { id: reviewId, status: 'APPROVED' } }); if (!review) throw new NotFoundException({ code: 'REVIEW_NOT_FOUND', message: 'Review was not found' }); const old = await tx.reviewVote.findUnique({ where: { reviewId_userId: { reviewId, userId } } }); await tx.reviewVote.upsert({ where: { reviewId_userId: { reviewId, userId } }, create: { reviewId, userId, helpful }, update: { helpful } }); const delta = (helpful ? 1 : 0) - (old?.helpful ? 1 : 0); if (delta) await tx.review.update({ where: { id: reviewId }, data: { helpfulCount: { increment: delta } } }); return { helpful }; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
}
