import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
@Injectable()
export class ReturnsService {
  constructor(private readonly prisma: PrismaService) {}
  list(userId: string) { return this.prisma.returnRequest.findMany({ where: { userId }, take: 100, orderBy: { createdAt: 'desc' }, include: { order: { select: { orderNumber: true } }, items: true, media: { include: { media: { select: { id: true, altText: true, mimeType: true, visibility: true } } } } } }); }
  async get(userId: string, id: string) { const request = await this.prisma.returnRequest.findFirst({ where: { id, userId }, include: { order: { select: { orderNumber: true } }, items: { include: { orderItem: true } }, media: { include: { media: { select: { id: true, altText: true, mimeType: true, visibility: true } } } } } }); if (!request) throw new NotFoundException({ code: 'RETURN_NOT_FOUND', message: 'Return request was not found' }); return request; }
  async create(userId: string, input: { orderId: string; reason: string; explanation: string; items: { orderItemId: string; quantity: number }[]; mediaIds?: string[] }) { return this.prisma.$transaction(async (tx) => { const order = await tx.order.findFirst({ where: { id: input.orderId, userId, status: 'DELIVERED' }, include: { items: true } }); if (!order || Date.now() - order.updatedAt.getTime() > 30 * 86_400_000) throw new ConflictException({ code: 'RETURN_NOT_ELIGIBLE', message: 'This order is not eligible for return' }); for (const requested of input.items) { const item = order.items.find((candidate) => candidate.id === requested.orderItemId); if (!item || requested.quantity > item.quantity) throw new ConflictException({ code: 'RETURN_QUANTITY_INVALID', message: 'Return quantity exceeds purchased quantity' }); const previous = await tx.returnItem.aggregate({ where: { orderItemId: item.id, request: { status: { not: 'REJECTED' } } }, _sum: { quantity: true } }); if ((previous._sum.quantity ?? 0) + requested.quantity > item.quantity) throw new ConflictException({ code: 'RETURN_ALREADY_REQUESTED', message: 'Items have already been included in another return' }); } const mediaIds = input.mediaIds ?? []; if (mediaIds.length && await tx.media.count({ where: { id: { in: mediaIds }, uploadedById: userId } }) !== mediaIds.length) throw new ConflictException({ code: 'RETURN_MEDIA_INVALID', message: 'One or more evidence images are unavailable' }); const request = await tx.returnRequest.create({ data: { orderId: order.id, userId, reason: input.reason, explanation: input.explanation, items: { create: input.items }, media: { create: mediaIds.map((mediaId) => ({ mediaId })) } } }); await tx.order.update({ where: { id: order.id }, data: { status: 'RETURN_REQUESTED' } }); await tx.orderStatusHistory.create({ data: { orderId: order.id, fromStatus: 'DELIVERED', toStatus: 'RETURN_REQUESTED', changedById: userId, notes: 'Customer submitted a return request' } }); return request; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
  async provideInformation(userId: string, id: string, input: { explanation: string; mediaIds?: string[] }) { return this.prisma.$transaction(async (tx) => { const request = await tx.returnRequest.findFirst({ where: { id, userId, status: 'MORE_INFO_REQUIRED' } }); if (!request) throw new ConflictException({ code: 'RETURN_INFORMATION_NOT_REQUESTED', message: 'This return is not waiting for more information' }); const mediaIds = input.mediaIds ?? []; if (mediaIds.length && await tx.media.count({ where: { id: { in: mediaIds }, uploadedById: userId } }) !== mediaIds.length) throw new ConflictException({ code: 'RETURN_MEDIA_INVALID', message: 'One or more evidence images are unavailable' }); await tx.returnMedia.createMany({ data: mediaIds.map((mediaId) => ({ returnId: id, mediaId })), skipDuplicates: true }); return tx.returnRequest.update({ where: { id }, data: { explanation: `${request.explanation ?? ''}\n\nAdditional information:\n${input.explanation}`, status: 'REQUESTED' }, include: { media: { include: { media: true } } } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
}
